language: node_js
cache: npm

matrix:
  include:
    - os: linux
      addons:
        chrome: stable
      node_js: 8.6
    - os: linux
      addons:
        chrome: stable
      node_js: node  # Latest
    - os: windows
      filter_secrets: false  # Secrets will otherwise break Windows builds
      node_js: 8.6
      script: npm run test:ava
    - os: windows
      filter_secrets: false  # Secrets will otherwise break Windows builds
      node_js: latest
      script: npm run test:ava

script:
  - npm test
