language: node_js

matrix:
  include:
    - os: linux
      addons:
        chrome: stable
      node_js: 8.6
    - os: linux
      addons:
        chrome: stable
      node_js: node  # Latest
    - os: windows
      filter_secrets: false  # Secrets will otherwise break Windows builds
      node_js: latest

script:
  - npm test
